server:
  port: 8080

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/video-channel-manager
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc/